apiVersion: v1
metadata:
  name: hello-anthem-s2i-pipeline
spec:
  strategy: 
    jenkinsPipelineStrategy:
      jenkinsfilePath: ${PIPELINE_SCRIPT}
    type: JenkinsPipeline
parameters:
- name: PIPELINE_SCRIPT
  value: Jenkinsfile
