kind: "BuildConfig"
apiVersion: v1
metadata:
  name: hello-anthem-s2i-pipeline
  #objects:
  #- kind: BuildConfig
spec:
        #source:
        #type: Git
        #git:
        #uri: https://github.com/otatman/hello-anthem-spring2.git
  strategy: 
    jenkinsPipelineStrategy:
            #jenkinsfilePath: ${PIPELINE_SCRIPT}
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
#parameters:
#- name: PIPELINE_SCRIPT
#  value: Jenkinsfile
