apiVersion: v1
kind: BuildConfig
metadata:
  name: hello-anthem-s2i-pipeline
spec:
  source:
    type: Git
    git:
      uri: https://github.com/otatman/hello-anthem-spring2.git     
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
