apiVersion: build.openshift.io/v1
kind: Build
metadata:
  labels:
    application: skopeo-agent
name: skopeo-agent
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'skopeo-agent:latest'
  source:
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7:latest
      USER root
      RUN yum repolist > /dev/null && yum-config-manager --enable rhel-7-server-extras-rpms &&  yum clean all &&  INSTALL_PKGS="skopeo" && yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && rpm -V $INSTALL_PKGS && yum clean all
      USER 1001
    type: Dockerfile
  strategy:
    dockerStrategy: {}
    type: Docker
